feature_extract_enable : 0
point_filter_num : 2
max_iteration : 10
dense_map_enable : 1
filter_size_surf : 0.15
filter_size_map : 0.3
cube_side_length : 20
debug : 0
grid_size : 40
patch_size : 8
img_enable : 1
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.001 # 0.001
cam_fx: 2052.596917996205
cam_fy: 2051.079911182952
cam_cx: 934.1643427174454
cam_cy: 780.2912775500538

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 4 # Livox Avia LiDAR
    scan_line: 6
    blind: 5 # blind x m disable

#  lidar_to_imu
mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    fov_degree:    90
    extrinsic_T: [ -1.73777, -0.0891784, 1.27162 ]
    extrinsic_R: [ -0.0532327 ,   0.966814 ,  -0.249875,
                   0.99855  , 0.0535356 ,-0.00558925
                   0.00797342   , -0.24981  , -0.968262]
# camera_to_lidar
camera:
    # img_topic: /usb_cam/image_raw
    img_topic:  /camera/image_color
    # img_topic: /left_camera/image
    #xiyuan
    Rcl: [0.00365494   ,  0.23507   , 0.971972,
        0.999865 , -0.0164238 ,0.000212261,
          0.0160134   ,  0.97184 ,  -0.235099]
    Pcl: [0.00569641, 0.0531469, 0.0729381]
    
